language: node_js
node_js:
  - 6

before_install:
  - npm i -g yarn

install: yarn

script:
  - yarn run flow
  - yarn test

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js